worker_processes  1;

events {
    worker_connections  4096;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;

    keepalive_timeout 65;

    # File Service 最大 request 为 310MB，
    # Nginx 留一些余量
    client_max_body_size 350m;

    server {
        listen 80;
        server_name music.3s.tunnelfrp.com localhost;

        # =====================================
        # 前端 React dist
        # 修改成你自己的真实路径
        # =====================================
        root D:\AveMusic\avemusic-web\dist;
        index index.html;

        # =====================================
        # React 前端
        # =====================================
        location / {
            try_files $uri $uri/ /index.html;
        }

        # =====================================
        # Gateway
        # /api/** -> 127.0.0.1:8080
        # =====================================
        location /api/ {
            proxy_pass http://127.0.0.1:8080;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_connect_timeout 30s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
        }

        # =====================================
        # File Service 上传
        # /upload/** -> 127.0.0.1:8090
        # =====================================
        location /upload/ {
            proxy_pass http://127.0.0.1:8090;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # 大文件上传
            client_max_body_size 350m;

            # 不先把整个文件缓存到 Nginx
            proxy_request_buffering off;
            proxy_buffering off;

            proxy_connect_timeout 30s;
            proxy_send_timeout 1800s;
            proxy_read_timeout 1800s;
            send_timeout 1800s;
        }

        # =====================================
        # File Service 文件读取
        # /files/** -> 127.0.0.1:8090
        # =====================================
        location /files/ {
            proxy_pass http://127.0.0.1:8090;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # 音乐播放器拖动进度条需要 Range
            proxy_set_header Range $http_range;
            proxy_set_header If-Range $http_if_range;

            proxy_buffering off;

            proxy_connect_timeout 30s;
            proxy_read_timeout 1800s;
            send_timeout 1800s;
        }
    }
}